import { useState } from 'react';
import { CreditCard, Check, ShieldCheck, ImagePlus, ArrowRightLeft } from 'lucide-react';
import { Button } from '../components/UI';
import { motorcycles } from '../data/motorcycles';
function Field({ label, name, type='text', required=true, ...props }) { return <label className="field"><span>{label}{!required&&' (opcional)'}</span><input name={name} type={type} required={required} maxLength={type==='text'?100:undefined} {...props}/></label>; }
function phoneValid(form){const input=form.elements.whatsapp; const digits=input.value.replace(/\D/g,'').length; const valid=digits>=10&&digits<=13; input.setCustomValidity(valid?'':'Informe um telefone com DDD, de 10 a 13 dígitos.'); if(!valid) input.reportValidity(); return valid;}
const phoneProps={type:'tel',autoComplete:'tel',placeholder:'(21) 99999-9999',maxLength:20,onInput:e=>e.currentTarget.setCustomValidity('')};
export function Financing({ onContact }) {
  function submit(e){e.preventDefault();if(!phoneValid(e.currentTarget))return; const f=Object.fromEntries(new FormData(e.currentTarget));onContact(`Olá! Gostaria de consultar um financiamento na Top Motos 021.\nNome: ${f.nome}\nWhatsApp: ${f.whatsapp}\nMoto de interesse: ${f.moto}\nEntrada aproximada: R$ ${f.entrada||'A combinar'}\nEstou ciente de que esta é uma consulta, sujeita à análise de crédito.`);}
  return <section className="section finance" id="financiamento"><div className="container split-layout"><div className="section-copy"><span className="eyebrow">MENOS DISTÂNCIA ENTRE VOCÊ E SEU SONHO</span><h2>Realize o sonho<br/>da <em>sua moto.</em></h2><p>A próxima conquista começa com uma conversa. Nossa equipe ajuda você a conhecer as possibilidades de financiamento para a moto que combina com seu momento.</p><ul className="check-list"><li><Check/>Atendimento próximo, do início ao fim</li><li><Check/>Consulta de condições para o seu perfil</li><li><Check/>Sua moto atual pode entrar na negociação</li></ul><div className="finance-note"><CreditCard/><span>Vamos encontrar o caminho<br/><b>para a sua próxima conquista.</b></span></div></div><form className="form-card" onSubmit={submit}><div className="form-heading"><CreditCard/><div><h3>Vamos dar o primeiro passo?</h3><p>Preencha e converse com um consultor.</p></div></div><div className="form-grid"><Field label="Seu nome" name="nome" autoComplete="name" placeholder="Como podemos te chamar?"/><Field label="Telefone / WhatsApp" name="whatsapp" {...phoneProps}/><label className="field"><span>Moto de interesse</span><select name="moto" defaultValue="" required><option value="" disabled>Selecione uma moto</option>{motorcycles.map(m=><option key={m.id} value={`${m.brand} ${m.model} (exemplo demonstrativo)`}>{m.brand} {m.model} · Exemplo</option>)}<option>Quero conhecer o estoque real</option></select></label><Field label="Entrada aproximada (R$)" name="entrada" type="number" min="0" max="1000000" step="100" placeholder="Ex.: 5.000" required={false}/></div><Button type="submit">QUERO SIMULAR MEU FINANCIAMENTO</Button><p className="form-disclaimer"><ShieldCheck size={15}/>Consulta sem compromisso. Sujeita à análise de crédito. Nenhuma aprovação é realizada por este site.</p><p className="data-note">Ao continuar, você prepara uma mensagem com seus dados para o atendimento. Nada é enviado automaticamente.</p></form></div></section>;
}
export function SellBike({ onContact }) {
  const [photoInfo,setPhotoInfo]=useState(false);
  function submit(e){e.preventDefault();if(!phoneValid(e.currentTarget))return;const f=Object.fromEntries(new FormData(e.currentTarget));onContact(`Olá! Quero avaliar minha moto para venda ou troca.\nNome: ${f.nome}\nWhatsApp: ${f.whatsapp}\nMarca: ${f.marca}\nModelo: ${f.modelo}\nAno: ${f.ano}\nQuilometragem: ${f.km} km\nValor pretendido: ${f.valor?'R$ '+f.valor:'A combinar'}\nObservações: ${f.observacoes||'Sem observações'}\nEnviarei as fotos diretamente na conversa.`);}
  return <section className="section sell" id="venda"><div className="container"><div className="sell-heading"><div><span className="eyebrow">NOVOS PLANOS? A GENTE NEGOCIA.</span><h2>Quer vender ou <em>trocar sua moto?</em></h2></div><p>Envie as informações da sua moto e fale com nossa equipe para receber uma avaliação.</p></div><form className="sell-form" onSubmit={submit}><div className="form-grid sell-fields"><Field label="Nome" name="nome" autoComplete="name" placeholder="Seu nome"/><Field label="WhatsApp" name="whatsapp" {...phoneProps}/><Field label="Marca" name="marca" placeholder="Ex.: Honda"/><Field label="Modelo" name="modelo" placeholder="Ex.: CG 160 Titan"/><Field label="Ano" name="ano" type="number" min="1900" max={new Date().getFullYear()+1} placeholder="Ex.: 2024"/><Field label="Quilometragem" name="km" type="number" min="0" max="2000000" placeholder="Ex.: 12.000"/><Field label="Valor pretendido (R$)" name="valor" type="number" min="0" max="1000000" step="100" required={false} placeholder="Ex.: 18.000"/><label className="field"><span>Observações (opcional)</span><textarea name="observacoes" maxLength="1000" placeholder="Conte um pouco sobre sua moto" rows="2"/></label></div><div className="sell-photo"><ImagePlus size={34}/><h3>Adicionar fotos da moto</h3><p>Mostre os detalhes da sua moto para nossa equipe.</p><button type="button" className="photo-button" onClick={()=>setPhotoInfo(!photoInfo)} aria-expanded={photoInfo}>COMO ENVIAR AS FOTOS<ArrowRightLeft size={16}/></button>{photoInfo?<p className="photo-explanation" role="status">Depois de abrir a conversa, use o botão de anexo do WhatsApp para enviar as fotos. Este site não recebe nem armazena arquivos.</p>:<small>Envio direto pelo WhatsApp após o contato.</small>}{/* INTEGRAÇÃO FUTURA: substituir esta orientação por input file e endpoint autenticado com validação de MIME, tamanho e armazenamento. Não simular upload. */}</div><div className="sell-submit"><p>Seus dados preparam uma mensagem. A avaliação é feita pela equipe após analisar a moto.</p><Button type="submit">QUERO AVALIAR MINHA MOTO</Button></div></form></div></section>;
}

